### ISSUE TITLE
Incompatibility with certain mods / Whitelist

### ISSUE THREAD

**Issue by Cramoisi-San** [ExterminatorX99/NoHotbarPickup#1]
hello,
I noticed that some mods, like Mystic Hunter, breaks when used alongside this mod. I was figuring that a easy fix would be to be able to whitelist some items to be able to go into the hotbar. For example, using said mod "Mystic Hunter", i could whitelist the item "Soul" so that it's mechanics works as intended.

**Comment by ExterminatorX99** [comment]
Could you elaborate on what exactly breaks?

**Comment by Cramoisi-San** [comment]
To explain it clearly, i first need to explain how the part of the mod that breaks works. Basically, vanilla monsters, when killed, rarely drops souls of their own species (a blue slime, for example, drops a blue slime soul). When collected, you gain their powers and can use them (think like Castelvania Aria of Sorrow, which is what the mod is based on). However, with your mod installed, the souls are collected incorrectly, putting them in your inventory without granting you the powers of the killed monster.

**Comment by ExterminatorX99** [comment]
Try the new update

**Comment by Cramoisi-San** [comment]
It works now, thank you
