### ISSUE TITLE
Hotkey tooltips obscure chest inventory

### ISSUE THREAD

**Issue by keyboard-cleric** [ExterminatorX99/NoHotbarPickup#2]
The tooltips make it difficult to see items in a chest:
"'Item' isn't in your blocked items."
"Press 'Insert' to block an item from entering your inventory."
"Press 'Delete' to block an item from entering your inventory."

It is helpful to have a tooltip warning that they hotkeys were not bound, but if these messages can't stay out of the way of the inventories themselves, then a config option to suppress these messages would be very welcome—especially once the user is comfortable with the hotkeys they've chosen.

![tModLoader_2021-07-16_194014](https://user-images.githubusercontent.com/87551492/126018223-9e931b1b-84b3-4f56-a3a6-42129f0f4d10.png)

**Comment by ExterminatorX99** [comment]
Ummm. This mod doesn't add any tooltips

**Comment by keyboard-cleric** [comment]
> Ummm. This mod doesn't add any tooltips

My apologies. I confused this mod with a mod named ItemBlocker.
